# Generated by Django 4.2.5 on 2023-09-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_rename_article_library'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Book',
        ),
    ]
