# Generated by Django 4.2.5 on 2023-09-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_rename_library_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Category_id',
            field=models.IntegerField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='Category_name',
            field=models.CharField(default='ABCD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
    ]
