# Generated by Django 4.2.6 on 2023-10-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='summary',
            new_name='description',
        ),
    ]
